import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Maximize2, X, BarChart3, Flame } from "lucide-react";
import { API_URL } from "../services/api";
import "./GraphGallery.css";

const absorptivityGraphs = [
  {
    id: "abs-corr",
    title: "Absorptivity Correlation Matrix",
    description: "Heatmap illustrating Pearson correlation between power, speed, line energy, and absorptivity.",
    image: `${API_URL}/figures/absorptivity_correlation_heatmap.png`,
    tag: "Correlation"
  },
  {
    id: "abs-power",
    title: "Power vs Absorptivity Trend",
    description: "Scatter and regression curve demonstrating the positive impact of laser power on laser absorption.",
    image: `${API_URL}/figures/absorptivity_power_vs_absorptivity.png`,
    tag: "Parameter Analysis"
  },
  {
    id: "abs-dist",
    title: "Absorptivity Percentage Distribution",
    description: "Histogram and Kernel Density Estimate (KDE) for absorptivity dataset distribution.",
    image: `${API_URL}/figures/absorptivity_absorptivity_pct_distribution.png`,
    tag: "Distribution"
  },
  {
    id: "abs-pair",
    title: "Absorptivity Multi-Variable Pairplot",
    description: "Pairwise relationships across all engineered input features for absorptivity modeling.",
    image: `${API_URL}/figures/absorptivity_pairplot.png`,
    tag: "Feature Space"
  }
];

const temperatureGraphs = [
  {
    id: "temp-corr",
    title: "Temperature Correlation Matrix",
    description: "Correlation heatmap identifying key thermal drivers including specific energy and line energy.",
    image: `${API_URL}/figures/interface_temperature_correlation_heatmap.png`,
    tag: "Correlation"
  },
  {
    id: "temp-line-energy",
    title: "Line Energy vs Interface Temp",
    description: "Direct linear physical relationship between energy density (J/mm) and peak interface temperature.",
    image: `${API_URL}/figures/interface_temperature_line_energy_vs_temperature.png`,
    tag: "Physics Relation"
  },
  {
    id: "temp-dist",
    title: "Interface Temperature Distribution",
    description: "KDE distribution graph showing weld joint interface thermal ranges (°C).",
    image: `${API_URL}/figures/interface_temperature_interface_temp_C_distribution.png`,
    tag: "Distribution"
  },
  {
    id: "temp-pair",
    title: "Temperature Feature Pairplot",
    description: "Multi-dimensional pairplot matrix for interface temperature predictors.",
    image: `${API_URL}/figures/interface_temperature_pairplot.png`,
    tag: "Feature Space"
  }
];

export default function GraphGallery() {
  const [selectedGraph, setSelectedGraph] = useState(null);

  return (
    <div className="gallery-section">
      <div className="gallery-header">
        <span className="section-badge">Exploratory Data Analysis</span>
        <h2>Dataset & Feature Visualizations</h2>
        <p>
          Empirical dataset distributions, feature correlations, and physics-informed parameter trends generated by the ML pipeline.
        </p>
      </div>

      {/* Absorptivity Section */}
      <div className="category-block">
        <div className="category-title">
          <div className="category-icon absorptivity-icon">
            <BarChart3 size={20} />
          </div>
          <div>
            <h3>Absorptivity Analysis</h3>
            <p>Optical absorption characteristics under varying power and speed profiles</p>
          </div>
        </div>

        <div className="gallery-grid">
          {absorptivityGraphs.map((graph) => (
            <motion.div
              key={graph.id}
              className="graph-card"
              whileHover={{ y: -6, scale: 1.02 }}
              transition={{ duration: 0.25 }}
              onClick={() => setSelectedGraph(graph)}
            >
              <div className="card-image-wrapper">
                <img src={graph.image} alt={graph.title} loading="lazy" />
                <div className="image-overlay">
                  <span className="expand-btn">
                    <Maximize2 size={16} /> Expand
                  </span>
                </div>
                <span className="card-tag">{graph.tag}</span>
              </div>
              <div className="card-info">
                <h4>{graph.title}</h4>
                <p>{graph.description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Temperature Section */}
      <div className="category-block">
        <div className="category-title">
          <div className="category-icon temperature-icon">
            <Flame size={20} />
          </div>
          <div>
            <h3>Interface Temperature Analysis</h3>
            <p>Thermal accumulation dynamics and line energy physics correlations</p>
          </div>
        </div>

        <div className="gallery-grid">
          {temperatureGraphs.map((graph) => (
            <motion.div
              key={graph.id}
              className="graph-card"
              whileHover={{ y: -6, scale: 1.02 }}
              transition={{ duration: 0.25 }}
              onClick={() => setSelectedGraph(graph)}
            >
              <div className="card-image-wrapper">
                <img src={graph.image} alt={graph.title} loading="lazy" />
                <div className="image-overlay">
                  <span className="expand-btn">
                    <Maximize2 size={16} /> Expand
                  </span>
                </div>
                <span className="card-tag temp-tag">{graph.tag}</span>
              </div>
              <div className="card-info">
                <h4>{graph.title}</h4>
                <p>{graph.description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Interactive Lightbox Modal */}
      <AnimatePresence>
        {selectedGraph && (
          <motion.div
            className="lightbox-backdrop"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setSelectedGraph(null)}
          >
            <motion.div
              className="lightbox-container"
              initial={{ scale: 0.9, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0, y: 20 }}
              transition={{ type: "spring", stiffness: 300, damping: 25 }}
              onClick={(e) => e.stopPropagation()}
            >
              <div className="lightbox-header">
                <div>
                  <span className="card-tag">{selectedGraph.tag}</span>
                  <h3>{selectedGraph.title}</h3>
                </div>
                <button
                  className="lightbox-close"
                  onClick={() => setSelectedGraph(null)}
                  aria-label="Close modal"
                >
                  <X size={20} />
                </button>
              </div>

              <div className="lightbox-body">
                <img src={selectedGraph.image} alt={selectedGraph.title} />
              </div>

              <div className="lightbox-footer">
                <p>{selectedGraph.description}</p>
                <span className="backend-link">Source: FastAPI Static Figures Endpoint</span>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}